### ISSUE TITLE
App not Updated since months

### ISSUE THREAD

**Issue by theunclemez** [flathub/org.flozz.yoga-image-optimizer#1]
Well, as a designer, I use yoga for divers purposes but mostly to send optimized but well compressed files to partners and client and I'm happy but still the app have not been updated since 2021 which for me is an issue.
Is the project still active or .... should I consider another program for the same purpose ?

**Comment by flozz** [comment]
Hello,

This project is not abandoned. I just work on (too) many projects and sometime I need to make pauses.

Currently there is no known bugs, so there is no need for "urgent" update. I have ideas to improve it (to improve both the GUI and the optimizations) and I will work on this in few months :)
